// import 'package:flutter/material.dart';
// import 'package:flutter/services.dart';
// // import 'package:';
// import 'package:country_code_picker/country_code_picker.dart';

// class CustomTextFormFieldWithCountryCode extends TextFormField {
//   const CustomTextFormFieldWithCountryCode({
//     Key? key,
//     String? initialValue,
//     TextEditingController? controller,
//     FocusNode? focusNode,
//     InputDecoration? decoration,
//     TextInputType? keyboardType,
//     TextCapitalization? textCapitalization,
//     TextInputAction? textInputAction,
//     TextStyle? style,
//     StrutStyle? strutStyle,
//     TextDirection? textDirection,
//     TextAlign? textAlign,
//     TextAlignVertical? textAlignVertical,
//     bool readOnly = false,
//     bool toolbarOptions = false,
//     bool showCursor = true,
//     bool autofocus = false,
//     String? obscuringCharacter,
//     bool obscureText = false,
//     bool autocorrect = true,
//     SmartDashesType? smartDashesType,
//     SmartQuotesType? smartQuotesType,
//     bool enableSuggestions = true,
//     MaxLengthEnforcement? maxLengthEnforcement,
//     int? maxLines = 1,
//     int? minLines,
//     bool expands = false,
//     int? maxLength,
//     bool? enabled,
//     void Function(String?)? onChanged,
//     void Function(String?)? onSubmitted,
//     EdgeInsets scrollPadding = const EdgeInsets.all(20.0),
//     bool enableInteractiveSelection = true,
//     InputCounter? inputCounter,
//     bool keepAlive = true,
//     GestureTapCallback? onTap,
//     VoidCallback? onEditingComplete,
//     List<TextInputFormatter>? inputFormatters,
//     bool autovalidate = false,
//     AutovalidateMode? autovalidateMode,
//     FormFieldSetter<String>? onSaved,
//     FormFieldValidator<String>? validator,
//     List<FormFieldValidator<String>>? validators,
//     Key? contextKey,
//     required CountryCodePicker countryPicker,
//   }) : super(
//     key: key,
//     initialValue: initialValue,
//     controller: controller,
//     focusNode: focusNode,
//     decoration: decoration,
//     keyboardType: keyboardType,
//     textCapitalization: textCapitalization,
//     textInputAction: textInputAction,
//     style: style,
//     strutStyle: strutStyle,
//     textDirection: textDirection,
//     textAlign: textAlign,
//     textAlignVertical: textAlignVertical,
//     readOnly: readOnly,
//     toolbarOptions: toolbarOptions,
//     showCursor: showCursor,
//     autofocus: autofocus,
//     obscuringCharacter: obscuringCharacter,
//     obscureText: obscureText,
//     autocorrect: autocorrect,
//     smartDashesType: smartDashesType,
//     smartQuotesType: smartQuotesType,
//     enableSuggestions: enableSuggestions,
//     maxLengthEnforcement: maxLengthEnforcement,
//     maxLines: maxLines,
//     minLines: minLines,
//     expands: expands,
//     maxLength: maxLength,
//     enabled: enabled,
//     onChanged: onChanged,
//     onSubmitted: onSubmitted,
//     scrollPadding: scrollPadding,
//     enableInteractiveSelection: enableInteractiveSelection,
//     inputCounter: inputCounter,
//     keepAlive: keepAlive,
//     onTap: onTap,
//     onEditingComplete: onEditingComplete,
//     inputFormatters: inputFormatters,
//     autovalidate: autovalidate,
//     autovalidateMode: autovalidateMode,
//     onSaved: onSaved,
//     validator: validator,
//     validators: validators,
//     contextKey: contextKey,
//   );
// }